services:
  mysqldb:
    image: mysql:latest
    container_name: devrank-mysql-container
    command: >
      --authentication_policy=mysql_native_password
      --pid-file=/pid/docker-mysql/mysqld.pid
    restart: unless-stopped
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: todolist_api
      MYSQL_USER: rian
      MYSQL_PASSWORD: 303huh303
      SERVICE_TAGS: development
      SERVICE_NAME: mysqldb
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
    networks:
      - internalnet

  nodeapp:
    container_name: devrank-nodejs-container
    build: .
    image: node:lts-slim
    ports:
      - 3030:3030
    expose:
      - 3030
    environment:
      DB_HOST: mysqldb
      DB_PORT: 3306
      DB_USER: "rian"
      DB_PASSWORD: "303huh303"
      DB_NAME: todolist_api
      NODE_ENV: production
      SERVICE_TAGS: production
      SERVICE_NAME: nodeappservice
      SERVER_PORT: 3030
    depends_on:
      - mysqldb
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
