services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqlcontainer
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./database/init/init.sql:/docker-entrypoint-initdb.d/0_init.sql
    ports:
      - 3306
    expose:
      - 3306
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=todolist_api
      - SERVICE_TAGS=dev
      - SERVICE_NAME=mysqldb
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
