services:
  mysqldb:
    image: mysql:8.0
    container_name: devrank-mysql-container
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: todolist_api
      MYSQL_USER: rian
      MYSQL_PASSWORD: 303huh303
      MYSQL_ROOT_PASSWORD: ""
      SERVICE_TAGS: development
      SERVICE_NAME: mysqldb
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
    networks:
      - internalnet

  nodeapp:
    container_name: devrank-nodejs-container
    build:
      context: .
      dockerfile: Dockerfile
    image: node:alpine
    ports:
      - 3030:3030
    expose:
      - 3030
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_PORT: 3306
      MYSQL_USER: "rian"
      MYSQL_PASSWORD: "303huh303"
      MYSQL_DBNAME: todolist_api
    depends_on:
      - mysqldb
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
